"""
Recognition Schemas

Request and response models for image recognition API endpoints.
Supports both mock and real recognition modes.
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field

from app.schemas.common import PaginatedResponse


class PredictionItem(BaseModel):
    """A single recognition prediction entry (top-5)."""

    rank: int = Field(ge=1, description="1-based prediction rank")
    character_name: str = Field(description="Recognized character name")
    confidence: float = Field(
        ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0"
    )
    work_title: str = Field(description="Anime/work title the character belongs to")


class RecognitionUploadResponse(BaseModel):
    """Response after uploading an image for recognition."""

    id: int = Field(description="Recognition log entry ID")
    status: str = Field(
        default="processing", description="Recognition status (processing/completed/failed)"
    )
    message: str = Field(
        default="Image uploaded successfully",
        description="Human-readable status message",
    )


class RecognitionResultResponse(BaseModel):
    """Full recognition result for a single image."""

    id: int = Field(description="Recognition log entry ID")
    image_url: str = Field(description="URL or path to the uploaded image")
    result: List[PredictionItem] = Field(
        min_length=1,
        description="Top-N predictions ranked by confidence",
    )
    confidence: Optional[float] = Field(
        default=None, ge=0.0, le=1.0, description="Top prediction confidence score"
    )
    top_character: Optional[str] = Field(
        default=None, description="Name of the top-ranked character"
    )
    is_mock: bool = Field(
        default=True, description="True if result was generated by mock recognizer"
    )
    created_at: datetime = Field(description="When the recognition was performed")

    model_config = {"from_attributes": True}


class RecognitionHistoryResponse(PaginatedResponse[RecognitionResultResponse]):
    """Paginated response for recognition history queries."""

    pass
